#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InforoadsWidgetAndroid.Resource", IsApplication=true)]

namespace InforoadsWidgetAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cloud = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int day_clear = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int day_cloudy = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int day_rain = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int day_snow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_launcher = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int night_clear = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int night_cloudy = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int night_rain = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int night_snow = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int widget = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int error_text = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int refresh_measuring_button = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int user_city_spinner = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int widgetBackground = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int widget_image = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int widget_temperature = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int widget_weather = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int city_name_brest = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int city_name_gomel = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int city_name_grodno = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int city_name_mikashevichi = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int city_name_minsk = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int city_name_mogilev = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int city_name_vitebsk = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int city_spinner_header = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int refresh_measuring_button = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int appwidgetprovider = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
